name: Build Docker Image

on:
  push:
    branches:
      - main # Modify this to match your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and tag Docker image
      run: |
        docker build -t my-image:v0.0.1-$(date +%s) -f path/to/Dockerfile .
      working-directory: ./path/to/context

    - name: Push Docker image to a registry (if needed)
      run: |
        # Use this step if you want to push the image to a container registry
        # docker push my-image:v0.0.1-$(date +%s)
      # You may need to set up Docker login and credentials here if pushing to a registry

    - name: Cleanup
      run: docker system prune -af
