name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
                  
    - name: Cache              
      uses: actions/cache@v3.3.2
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.0
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Build the Docker image
      run: docker build . --file ConectaPet --tag v0.0.1:$(date +%s)
